package `in`.aicortex.iso8583studio.ui.screens.apduSimulator.v2

/**
 * Human-readable labels for INS bytes, status words, and EMV tags. Used by the Card Session view
 * and the Trace Log to annotate raw hex with what it actually means.
 */

internal fun insName(ins: Int): String = when (ins) {
    0xA4 -> "SELECT"
    0xA8 -> "GET PROCESSING OPTIONS"
    0xB2 -> "READ RECORD"
    0xB0 -> "READ BINARY"
    0xCA -> "GET DATA"
    0x84 -> "GET CHALLENGE"
    0x20 -> "VERIFY"
    0xAE -> "GENERATE AC"
    0x88 -> "INTERNAL AUTHENTICATE"
    0x82 -> "EXTERNAL AUTHENTICATE"
    0x24 -> "CHANGE REFERENCE DATA"
    0x2C -> "RESET RETRY COUNTER"
    0xDA -> "PUT DATA"
    0xD6 -> "UPDATE BINARY"
    0xDC -> "UPDATE RECORD"
    0xE2 -> "APPEND RECORD"
    0xE4 -> "DELETE FILE"
    0xC0 -> "GET RESPONSE"
    else -> "(unknown)"
}

internal fun swMeaning(sw: Int): String = when (sw) {
    0x9000 -> "Success"
    0x6100 -> "Bytes remaining (use GET RESPONSE)"
    0x6200 -> "Warning — NV memory unchanged"
    0x6300 -> "Warning — NV memory changed"
    0x6400 -> "Execution error"
    0x6700 -> "Wrong length"
    0x6881 -> "Logical channel not supported"
    0x6882 -> "Secure messaging not supported"
    0x6900 -> "Command not allowed"
    0x6981 -> "Command incompatible with file structure"
    0x6982 -> "Security status not satisfied"
    0x6983 -> "Authentication method blocked"
    0x6984 -> "Reference data invalidated"
    0x6985 -> "Conditions of use not satisfied"
    0x6986 -> "Command not allowed (no current EF)"
    0x6A80 -> "Wrong data"
    0x6A81 -> "Function not supported"
    0x6A82 -> "File not found"
    0x6A83 -> "Record not found"
    0x6A86 -> "Incorrect P1 / P2"
    0x6A87 -> "Lc inconsistent with P1 / P2"
    0x6A88 -> "Referenced data not found"
    0x6B00 -> "Wrong P1 / P2"
    0x6D00 -> "INS not supported"
    0x6E00 -> "CLA not supported"
    0x6F00 -> "Unknown error"
    else -> when {
        sw and 0xFF00 == 0x6100 -> "Bytes remaining: %d".format(sw and 0xFF)
        sw and 0xFF00 == 0x6C00 -> "Wrong Le — correct Le=%d".format(sw and 0xFF)
        sw and 0xFFF0 == 0x63C0 -> "PIN tries remaining: %d".format(sw and 0xF)
        else -> "(unknown SW)"
    }
}

internal fun tagName(tag: Int): String = when (tag) {
    0x4F -> "Application Identifier (AID)"
    0x50 -> "Application Label"
    0x57 -> "Track 2 Equivalent Data"
    0x5A -> "Application PAN"
    0x5F20 -> "Cardholder Name"
    0x5F24 -> "Application Expiration Date"
    0x5F25 -> "Application Effective Date"
    0x5F28 -> "Issuer Country Code"
    0x5F2A -> "Transaction Currency Code"
    0x5F2D -> "Language Preference"
    0x5F30 -> "Service Code"
    0x5F34 -> "Application PAN Sequence Number"
    0x61 -> "Application Template"
    0x6F -> "FCI Template"
    0x70 -> "READ RECORD Response Template"
    0x77 -> "Response Template Format 2"
    0x80 -> "Response Template Format 1"
    0x82 -> "Application Interchange Profile (AIP)"
    0x83 -> "Command Template"
    0x84 -> "Dedicated File (DF) Name"
    0x87 -> "Application Priority Indicator"
    0x88 -> "Short File Identifier (SFI)"
    0x8C -> "CDOL1"
    0x8D -> "CDOL2"
    0x8E -> "CVM List"
    0x8F -> "CA Public Key Index"
    0x90 -> "Issuer Public Key Certificate"
    0x92 -> "Issuer PK Remainder"
    0x93 -> "Signed Static Application Data"
    0x94 -> "Application File Locator (AFL)"
    0x95 -> "Terminal Verification Results (TVR)"
    0x97 -> "Transaction Certificate DOL (TDOL)"
    0x9A -> "Transaction Date"
    0x9B -> "Transaction Status Information (TSI)"
    0x9C -> "Transaction Type"
    0x9F02 -> "Amount, Authorised (Numeric)"
    0x9F03 -> "Amount, Other (Numeric)"
    0x9F05 -> "Application Discretionary Data"
    0x9F07 -> "Application Usage Control"
    0x9F08 -> "Application Version Number"
    0x9F0D -> "Issuer Action Code — Default"
    0x9F0E -> "Issuer Action Code — Denial"
    0x9F0F -> "Issuer Action Code — Online"
    0x9F10 -> "Issuer Application Data (IAD)"
    0x9F11 -> "Issuer Code Table Index"
    0x9F12 -> "Application Preferred Name"
    0x9F13 -> "Last Online ATC Register"
    0x9F17 -> "PIN Try Counter"
    0x9F1A -> "Terminal Country Code"
    0x9F1C -> "Terminal Identification"
    0x9F1E -> "IFD Serial Number"
    0x9F21 -> "Transaction Time"
    0x9F26 -> "Application Cryptogram (AC)"
    0x9F27 -> "Cryptogram Information Data (CID)"
    0x9F32 -> "Issuer Public Key Exponent"
    0x9F33 -> "Terminal Capabilities"
    0x9F34 -> "CVM Results"
    0x9F35 -> "Terminal Type"
    0x9F36 -> "Application Transaction Counter (ATC)"
    0x9F37 -> "Unpredictable Number"
    0x9F38 -> "PDOL"
    0x9F40 -> "Additional Terminal Capabilities"
    0x9F42 -> "Application Currency Code"
    0x9F45 -> "Data Authentication Code"
    0x9F46 -> "ICC Public Key Certificate"
    0x9F47 -> "ICC Public Key Exponent"
    0x9F48 -> "ICC Public Key Remainder"
    0x9F49 -> "DDOL"
    0x9F4A -> "SDA Tag List"
    0x9F4C -> "ICC Dynamic Number"
    0x9F4D -> "Log Entry"
    0x9F4F -> "Log Format"
    0xA5 -> "FCI Proprietary Template"
    0xBF0C -> "FCI Issuer Discretionary Data"
    else -> "(tag $%X)".format(tag)
}
