package `in`.aicortex.iso8583studio.ui.navigation

/**
 * Navigation destinations for the app
 */
sealed class Screen {
    object GatewayType : Screen()
    object TransmissionSettings : Screen()
    object KeySettings : Screen()
    object LogSettings : Screen()
    object AdvancedOptions : Screen()
    object Monitor : Screen()
    object HostSimulator : Screen()
    object EMV4_1 : Screen()
    object EMV4_2 : Screen()
    object EMVMasterCardCrypto: Screen()
    object EMVVsdcCrypto: Screen()
    object SDA : Screen()
    object DDA : Screen()
    object ICCDynamicNumberMasterCard : Screen()
    object DataStoragePartialKeyMaterCard : Screen()
    object SecureMessagingMasterCard : Screen()
    object SecureMessagingVisa : Screen()
    object HceVisa : Screen()
    object CapTokenComputation : Screen()
    object AtrParser : Screen()
    object EmvDataParser : Screen()
    object EmvTagDictionary : Screen()
    object ApduResponseQuery : Screen()
    object HashCalculator : Screen()
    object CharacterEncoder : Screen()
    object BcdCalculator : Screen()
    object CheckDigit : Screen()
    object Base64Calculator : Screen()
    object Base94Calculator : Screen()
    object MessageParser : Screen()
    object RsaDerPubKeyCalculator : Screen()
    object AesCalculator : Screen()
    object DesCalculator : Screen()
    object RsaCalculator : Screen()
    object ThalesRsaCalculator : Screen()
    object EcdsaCalculator : Screen()
    object FpeCalculator : Screen()
    object DeaKeyCalculator : Screen()
    object KeyshareGenerator : Screen()
    object FuturexKeyCalculator : Screen()
}