package `in`.aicortex.iso8583studio.domain.service.posSimulatorService.avd

import `in`.aicortex.iso8583studio.domain.service.posSimulatorService.device.AvdProperties
import `in`.aicortex.iso8583studio.domain.service.posSimulatorService.device.AvdSpec
import `in`.aicortex.iso8583studio.domain.service.posSimulatorService.device.HardwareProfile
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.FlowCollector
import kotlinx.coroutines.flow.flow
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.exists
import kotlin.io.path.isDirectory

/**
 * Creates and maintains the AVD behind a POS simulator — **without `avdmanager`**.
 *
 * An AVD is just a directory, and everything substantial in it (`userdata-qemu.img`, `cache.img`,
 * `hardware-qemu.ini`, snapshots) is generated by the emulator on first boot. Creating one needs
 * only: the `<name>.avd` directory, a `config.ini`, the `<name>.ini` pointer that makes it visible
 * to Android Studio, and a 1 MB `userdata.img` seed copied from the system image.
 *
 * Not using `avdmanager` is a necessity, not a preference:
 *
 *  - It **cannot be pointed at a different SDK**. It derives the root from its own install location
 *    (`-Dcom.android.sdkmanager.toolsdir`) and ignores `ANDROID_SDK_ROOT`; `--sdk_root` is accepted
 *    by `sdkmanager` but rejected outright by `create avd`. Where the cmdline-tools come from
 *    Homebrew and the images live in `~/Library/Android/sdk`, it reports zero installed images.
 *  - It **cannot set RAM or screen geometry** anyway — the two things a device replica most needs.
 *  - Passing `-d` to pick a device definition makes it stamp a `hw.device.hash2` that then drifts
 *    permanently against our model and triggers Studio's "device definition has changed" nag.
 *
 * Writing the files ourselves is deterministic, needs no cmdline-tools installed, is testable
 * without any SDK tooling, and is the only way the 153-property editor can mean anything.
 */
class AvdManagerService(private val sdk: AndroidSdk) {

    /**
     * Creates or updates the AVD, emitting a step per phase.
     *
     * Idempotent: an AVD that already exists with matching content short-circuits at [AvdPhase.VERIFY]
     * without touching disk, so this is safe to call before every boot.
     */
    fun prepare(
        spec: AvdSpec,
        hardware: HardwareProfile,
        mode: PrepareMode = PrepareMode.AUTO,
    ): Flow<AvdStep> = flow {
        val avdName = spec.avdName.ifBlank { "" }

        // ---- validate ----
        emit(AvdStep.PhaseStart(now(), AvdPhase.VALIDATE))
        if (avdName.isBlank()) {
            abort(AvdPhase.VALIDATE, "AVD name is empty.", "Set a name on the System & Boot tab.")
            return@flow
        }
        if (!AvdProperties.isManaged(avdName)) {
            // The guard that protects hand-built AVDs sitting in the same directory.
            abort(
                AvdPhase.VALIDATE,
                "\"$avdName\" is not a managed AVD.",
                "Managed AVDs must start with \"${AvdProperties.MANAGED_PREFIX}\" so this tool can " +
                    "never create or delete an AVD you built yourself.",
            )
            return@flow
        }

        val schema = HardwarePropertiesSchema.load(sdk.root)
        val image = spec.systemImage.withHostAbi()
        val installed = SystemImageCatalog.scanInstalled(sdk)
        val issues = AvdValidator.validate(
            AvdValidationInput(
                avdName = avdName,
                properties = AvdProperties.effective(spec, hardware, schema),
                image = image,
                installedImages = installed.map { it.ref },
                skin = hardware.skin?.path?.takeIf { it.isNotBlank() }
                    ?.let { runCatching { SkinCatalog.read(Path.of(it)) }.getOrNull() },
            )
        )
        issues.forEach {
            emit(AvdStep.Line(now(), AvdPhase.VALIDATE, "${it.severity}: ${it.message}", it.severity == Severity.ERROR))
        }
        val blocking = issues.filter { it.severity == Severity.ERROR }
        if (blocking.isNotEmpty()) {
            abort(
                AvdPhase.VALIDATE,
                blocking.joinToString("; ") { it.message },
                blocking.first().remediation,
            )
            return@flow
        }
        emit(AvdStep.PhaseEnd(now(), AvdPhase.VALIDATE, ok = true))

        // ---- resolve image ----
        emit(AvdStep.PhaseStart(now(), AvdPhase.RESOLVE_IMAGE))
        emit(AvdStep.Line(now(), AvdPhase.RESOLVE_IMAGE, "Using ${image.sdkPackage}"))
        emit(AvdStep.PhaseEnd(now(), AvdPhase.RESOLVE_IMAGE, ok = true))

        val avdDir = sdk.avdHome.resolve("$avdName.avd")
        val pointer = sdk.avdHome.resolve("$avdName.ini")
        val configPath = avdDir.resolve("config.ini")
        val desired = AvdProperties.configIniOverlay(spec, hardware)

        // ---- short-circuit when nothing needs doing ----
        val exists = avdDir.isDirectory() && configPath.exists()
        if (exists && mode == PrepareMode.AUTO) {
            val current = ConfigIni.read(configPath)
            val drifted = desired.filter { (k, v) -> current[k] != schema.normalize(k, v) }
            if (drifted.isEmpty()) {
                emit(AvdStep.PhaseStart(now(), AvdPhase.VERIFY))
                emit(AvdStep.Line(now(), AvdPhase.VERIFY, "AVD already matches this configuration."))
                emit(AvdStep.PhaseEnd(now(), AvdPhase.VERIFY, ok = true))
                emit(AvdStep.Done(now(), summary = "$avdName is up to date (${current.size} keys)."))
                return@flow
            }
            emit(AvdStep.PhaseStart(now(), AvdPhase.WRITE_CONFIG))
            emit(AvdStep.Line(now(), AvdPhase.WRITE_CONFIG, "${drifted.size} setting(s) changed; patching in place."))
            drifted.forEach { (k, v) ->
                emit(AvdStep.Line(now(), AvdPhase.WRITE_CONFIG, "  $k: ${current[k] ?: "(unset)"} -> $v"))
            }
            current.withOverlay(desired, schema).write(configPath)
            emit(AvdStep.PhaseEnd(now(), AvdPhase.WRITE_CONFIG, ok = true))
            emit(AvdStep.Done(now(), summary = "$avdName updated without recreating; user data preserved."))
            return@flow
        }

        // ---- create the AVD directory ourselves ----
        emit(AvdStep.PhaseStart(now(), AvdPhase.CREATE_AVD))
        if (mode == PrepareMode.RECREATE && avdDir.exists()) {
            emit(AvdStep.Line(now(), AvdPhase.CREATE_AVD, "Removing existing $avdDir"))
            deleteDirectory(avdDir)
        }

        val imageDir = sdk.root.resolve(image.sysdir)
        if (!imageDir.isDirectory()) {
            abort(
                AvdPhase.CREATE_AVD,
                "System image directory not found: $imageDir",
                "Install it with: sdkmanager --sdk_root=${sdk.root} \"${image.sdkPackage}\"",
            )
            return@flow
        }

        Files.createDirectories(avdDir)
        emit(AvdStep.Line(now(), AvdPhase.CREATE_AVD, "Created $avdDir"))

        // The only binary an AVD needs up front. The emulator expands this 1 MB seed into
        // userdata-qemu.img on first boot and generates cache.img, hardware-qemu.ini, snapshots and
        // the rest itself — which is why creating an AVD needs no SDK tool at all.
        val userdataSrc = imageDir.resolve("userdata.img")
        val userdataDst = avdDir.resolve("userdata.img")
        if (userdataSrc.exists() && !userdataDst.exists()) {
            Files.copy(userdataSrc, userdataDst)
            emit(AvdStep.Line(now(), AvdPhase.CREATE_AVD, "Seeded userdata.img from the system image"))
        } else if (!userdataSrc.exists()) {
            emit(AvdStep.Line(now(), AvdPhase.CREATE_AVD, "No userdata.img in the image; the emulator will create one."))
        }
        emit(AvdStep.PhaseEnd(now(), AvdPhase.CREATE_AVD, ok = true))

        // ---- write config.ini ----
        emit(AvdStep.PhaseStart(now(), AvdPhase.WRITE_CONFIG))
        // Merge onto whatever is already there (nothing on a fresh create), so keys we do not model
        // survive a re-prepare — the forward-compatibility guarantee for newer emulator properties.
        val merged = ConfigIni.read(configPath).withOverlay(desired, schema)
        merged.write(configPath)
        emit(AvdStep.Line(now(), AvdPhase.WRITE_CONFIG, "Wrote ${merged.size} keys to config.ini"))
        emit(AvdStep.Line(now(), AvdPhase.WRITE_CONFIG, "  all ${desired.size} set from the device profile"))
        emit(AvdStep.PhaseEnd(now(), AvdPhase.WRITE_CONFIG, ok = true))

        // ---- pointer ini ----
        emit(AvdStep.PhaseStart(now(), AvdPhase.WRITE_POINTER))
        ConfigIni.pointerIni(avdDir, image.apiLevel).write(pointer)
        emit(AvdStep.Line(now(), AvdPhase.WRITE_POINTER, "Wrote $pointer"))
        emit(AvdStep.Line(now(), AvdPhase.WRITE_POINTER, "This is what makes the AVD visible to avdmanager and Android Studio."))
        emit(AvdStep.PhaseEnd(now(), AvdPhase.WRITE_POINTER, ok = true))

        // ---- verify ----
        emit(AvdStep.PhaseStart(now(), AvdPhase.VERIFY))
        val reread = ConfigIni.read(configPath)
        // Compare against the canonical form, not the raw desired value: the writer normalises
        // through the schema, so a boolean asked for as "false" is written as "no" and a size asked
        // for as "6442450944" is written as "6G". Both are the same setting.
        val mismatched = desired.filter { (k, v) -> reread[k] != schema.normalize(k, v) }
        if (mismatched.isNotEmpty()) {
            mismatched.forEach { (k, v) ->
                emit(AvdStep.Line(now(), AvdPhase.VERIFY, "  $k expected \"$v\", found \"${reread[k]}\"", true))
            }
            abort(AvdPhase.VERIFY, "config.ini did not persist ${mismatched.size} setting(s).", "Check filesystem permissions.")
            return@flow
        }
        emit(AvdStep.Line(now(), AvdPhase.VERIFY, "All ${desired.size} settings verified on disk."))
        emit(AvdStep.PhaseEnd(now(), AvdPhase.VERIFY, ok = true))

        emit(AvdStep.Done(now(), summary = "$avdName created at $avdDir"))
    }

    /**
     * Deletes a managed AVD — directory and pointer both, which is all `avdmanager delete` does
     * (and it is known to leave the pointer behind, stranding a broken entry in Device Manager).
     *
     * Refuses anything without the managed prefix.
     */
    fun delete(avdName: String): Boolean {
        require(AvdProperties.isManaged(avdName)) {
            // Not defensive noise: ~/.android/avd holds hand-built AVDs, and an unguarded delete
            // here would be a data-loss bug.
            "Refusing to delete \"$avdName\" — only AVDs prefixed \"${AvdProperties.MANAGED_PREFIX}\" are managed."
        }
        val dir = sdk.avdHome.resolve("$avdName.avd")
        val removedDir = if (dir.isDirectory()) { deleteDirectory(dir); true } else false
        val removedPointer = runCatching { Files.deleteIfExists(sdk.avdHome.resolve("$avdName.ini")) }
            .getOrDefault(false)
        return removedDir || removedPointer
    }

    private fun deleteDirectory(dir: Path) {
        Files.walk(dir).use { stream ->
            stream.sorted(Comparator.reverseOrder()).forEach { runCatching { Files.delete(it) } }
        }
    }

    fun exists(avdName: String): Boolean =
        sdk.avdHome.resolve("$avdName.avd").isDirectory() &&
            sdk.avdHome.resolve("$avdName.avd/config.ini").exists()

    private suspend fun FlowCollector<AvdStep>.abort(phase: AvdPhase, reason: String, remediation: String) {
        emit(AvdStep.PhaseEnd(now(), phase, ok = false))
        emit(AvdStep.Aborted(now(), phase, reason, remediation))
    }

    private fun now() = System.currentTimeMillis()
}

enum class PrepareMode {
    /** Create if missing, patch in place if it exists and has drifted. */
    AUTO,

    /** Always recreate from scratch, wiping user data. */
    RECREATE,
}
