/**
 * One-shot import of the 32 non-blog pages from docs/ into route + content
 * modules.
 *
 * Each source page is a full document wrapped in <site-header>/<site-footer>
 * custom elements. Those become the Angular shell, the <head> metadata becomes
 * route data, and the body becomes a content module rendered by StaticPage.
 *
 * Every internal href is resolved against the source page's directory and then
 * rewritten to its extensionless route, which is what removes .html from the
 * site without leaving a broken link behind.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { join, dirname, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalise, ownedClasses, TOKEN_ALIASES } from './css-codemod.mjs';


const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
/** Custom properties the design system already declares. */
const SYSTEM_TOKENS = new Set(
  [...readFileSync(join(ROOT, 'src/styles/_tokens.css'), 'utf8')
    .matchAll(/^\s*(--[\w-]+)\s*:/gm)].map((m) => m[1]),
);
const DOCS = join(ROOT, '..', 'docs');
const OUT_PAGES = join(ROOT, 'src/app/content/pages');
const OUT_CSS = join(ROOT, 'src/styles/pages');
const OUT_DIR = join(ROOT, 'src/app/content');

/** source file -> { id, path } */
const PAGES = [
  ['index.html', 'home', '/'],
  ['privacy-policy.html', 'privacy-policy', '/privacy-policy'],
  ['terms-and-conditions.html', 'terms-and-conditions', '/terms-and-conditions'],
  ...['cloud-simulators', 'contact', 'emv-certification', 'kernel', 'middleware', 'pro']
    .map((s) => [`${s}/index.html`, s, `/${s}`]),
  ['docs/index.html', 'docs', '/docs'],
  ...[
    'apdu-simulator', 'atm-simulator', 'card-validation', 'cipher-tools', 'contributing',
    'dukpt-tools', 'ecr-simulator', 'emv-tools', 'host-simulator', 'hsm-command-console',
    'hsm-simulator', 'installation', 'issuer-simulator', 'key-tools', 'mac-tools',
    'payment-simulators', 'payment-switch', 'pin-tools', 'pos-simulator', 'utility-tools',
    'versions',
  ].map((s) => [`docs/${s}/index.html`, `docs-${s}`, `/docs/${s}`]),
];

const fromDirOf = (file) => (dirname(file) === '.' ? '' : dirname(file));

const attr = (tag, name) => {
  const m = tag.match(new RegExp(`${name}\\s*=\\s*"([^"]*)"`, 'i'));
  return m ? m[1] : undefined;
};

const decode = (s) => (s ?? '')
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'");

function metaFrom(head, key, kind = 'name') {
  const re = new RegExp(`<meta[^>]*${kind}\\s*=\\s*["']${key}["'][^>]*>`, 'i');
  const tag = head.match(re);
  return tag ? decode(attr(tag[0], 'content')) : undefined;
}

/** Resolve an href written relative to `fromDir` into a clean site route. */
function rewriteHref(href, fromDir, pagePath = '') {
  if (!href) return href;

  /* Angular needs <base href="/">, and per the HTML spec a fragment-only href
     resolves against the document base URL rather than the current URL. So
     `href="#aes"` pointed at the site root — every in-page anchor navigated
     home. Qualifying them with the page's own path fixes that for the router
     and for anyone without JavaScript alike. */
  if (href.startsWith('#')) return `${pagePath}${href}`;

  if (/^(https?:|mailto:|tel:|data:|javascript:)/i.test(href)) return href;

  const [pathPart, hash = ''] = href.split('#');
  const suffix = hash ? `#${hash}` : '';
  if (!pathPart) return href;

  // Root-absolute already (e.g. /assets/..., /images/...).
  let resolved = pathPart.startsWith('/')
    ? pathPart.slice(1)
    : posix.normalize(posix.join(fromDir, pathPart));
  // normalize() leaves "./" and "." for a link to the current directory, which
  // would otherwise be emitted as the literal path "/.".
  if (resolved === '.' || resolved === './') resolved = '';
  resolved = resolved.replace(/^\.\//, '');

  if (resolved.startsWith('images/')) return `/${resolved}${suffix}`;
  if (resolved.startsWith('assets/')) return `/${resolved}${suffix}`;

  let route = resolved
    .replace(/index\.html$/, '')
    .replace(/\.html$/, '')
    .replace(/\/$/, '');

  return `/${route}${suffix}`.replace(/^\/$/, '/') || '/';
}

const PRO_NUDGE = (label) => `<aside class="pro-nudge"><span class="pn-tag">✦ Pro</span>` +
  `<p>${label} Pro raises the CPS ceiling, unlocks the full algorithm set and deep simulator ` +
  `tweaks, plus hosted endpoints and priority support.</p>` +
  `<a href="/pro">Register for Pro →</a></aside>`;

rmSync(OUT_PAGES, { recursive: true, force: true });
rmSync(OUT_CSS, { recursive: true, force: true });
mkdirSync(OUT_PAGES, { recursive: true });
mkdirSync(OUT_CSS, { recursive: true });

const banner = '// GENERATED by tools/import-pages.mjs — do not edit.\n';
const routes = [];
const cssFiles = [];
let missing = 0;
let droppedRules = 0;

// Read the design system's own stylesheets so the codemod knows what it owns.
const OWNED = ownedClasses(
  ['_base.css', '_components.css', '_prose.css']
    .map((f) => readFileSync(join(ROOT, 'src/styles', f), 'utf8')),
);

for (const [file, id, path] of PAGES) {
  const src = join(DOCS, file);
  if (!existsSync(src)) { console.warn(`  MISSING ${file}`); missing++; continue; }

  const raw = readFileSync(src, 'utf8');
  const head = raw.match(/<head[^>]*>([\s\S]*?)<\/head>/i)?.[1] ?? '';
  let body = raw.match(/<body[^>]*>([\s\S]*?)<\/body>/i)?.[1] ?? '';

  // ---- head -------------------------------------------------------------
  const title = decode(head.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim() ?? id);
  const description = metaFrom(head, 'description');
  const keywords = metaFrom(head, 'keywords');
  const robots = metaFrom(head, 'robots');
  const author = metaFrom(head, 'author');
  const ogType = metaFrom(head, 'og:type', 'property') ?? 'website';
  const image = metaFrom(head, 'og:image', 'property');

  const jsonLd = [...head.matchAll(
    /<script[^>]*application\/ld\+json[^>]*>([\s\S]*?)<\/script>/gi,
  )].map((m) => {
    try { return JSON.parse(m[1]); } catch { return null; }
  }).filter(Boolean);

  // Structured data still carries .html URLs from the old generator.
  const cleanUrls = (node) => {
    if (typeof node === 'string') {
      return node.replace(/^(https:\/\/iso8583\.studio)(\/[^\s"]*)$/i, (_, o, p) =>
        o + p.replace(/index\.html$/, '').replace(/\.html$/, ''));
    }
    if (Array.isArray(node)) return node.map(cleanUrls);
    if (node && typeof node === 'object') {
      return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, cleanUrls(v)]));
    }
    return node;
  };

  // ---- inline page CSS --------------------------------------------------
  /* A page's own styles can arrive two ways: an inline <style>, or a <link> to
     a stylesheet that is not one of the two site-wide ones. docs/emv-tools is
     the only page using the latter — it links docs/_shared.css and does not
     load site.css at all — and reading only inline styles silently dropped
     14.9 KB of it. */
  const sheetHrefs = [...head.matchAll(/<link[^>]+rel=["']stylesheet["'][^>]*>/gi)]
    .map((m) => attr(m[0], 'href'))
    .filter(Boolean);
  const usedSiteCss = sheetHrefs.some((h) => /assets\/site\.css$/.test(h));

  const linked = sheetHrefs
    .filter((href) => href && !/^https?:/i.test(href) && !/assets\/(site|solutions)\.css$/.test(href))
    .map((href) => {
      const abs = join(DOCS, posix.normalize(posix.join(fromDirOf(file), href)));
      if (!existsSync(abs)) { console.warn(`  MISSING stylesheet ${href} for ${file}`); return ''; }
      return readFileSync(abs, 'utf8');
    });

  const styles = [
    ...[...head.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map((m) => m[1]),
    ...linked,
  ].join('\n');
  if (styles.trim()) {
    const { css, dropped } = normalise(styles, OWNED, `.page-${id}`, SYSTEM_TOKENS);
    /* docs/emv-tools ships its own stylesheet and never loaded site.css, so it
       was never subject to the shared heading treatment. The design system now
       applies site-wide, and supplies properties that page's sheet does not
       declare. Hand those back so the page keeps the typography it shipped
       with; drop this block if it should adopt the system instead. */
    const shim = usedSiteCss ? '' : `
.page-${id} .page-title {
    letter-spacing: normal;
    background: none;
    color: var(--text);
    -webkit-text-fill-color: currentColor;
}
.page-${id} .doc-section h2 { letter-spacing: normal; }
.page-${id} .breadcrumb { flex-wrap: nowrap; }
/* site.css declares .steps margin with !important, to beat the generic list
   margin. A page that never loaded site.css never saw that, so matching it
   needs the same weight. */
.page-${id} .steps,
.page-${id} .doc-section .steps { margin: 0 0 16px 24px !important; }
`;

    if ((css + shim).trim()) {
      writeFileSync(join(OUT_CSS, `${id}.css`),
        `/* Imported from docs/${file}.\n` +
        `   tools/css-codemod.mjs dropped the token blocks and every rule the design\n` +
        `   system already owns, then scoped what remained to .page-${id} so these\n` +
        `   page-specific styles cannot leak onto the rest of the site. */\n${css}\n${shim}`);
      cssFiles.push(`${id}.css`);
    }
    droppedRules += dropped;
  }

  // ---- body -------------------------------------------------------------
  const fromDir = fromDirOf(file);

  body = body
    .replace(/<site-header[\s\S]*?<\/site-header>/gi, '')
    .replace(/<site-footer[\s\S]*?<\/site-footer>/gi, '')
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<site-pro([^>]*)><\/site-pro>/gi, (_, a) =>
      PRO_NUDGE(decode(attr(`<x${a}>`, 'label')) ||
        'Testing with a team, or certifying with a scheme?'))
    // The simulator tiles shipped with a `loading` skeleton that the page's
    // inline script removed once it ran. Prerendering means the content is
    // already there, so the skeleton would only blank the tiles for anyone
    // without JavaScript.
    .replace(/class="simtile loading"/g, 'class="simtile"');

  // Rewrite every internal href/src to its clean route.
  body = body.replace(/\b(href|src)="([^"]*)"/gi,
    (_, a, v) => `${a}="${rewriteHref(v, fromDir, path)}"`);

  /* Inline style attributes reference custom properties too. Renaming the
     retired tokens only inside the stylesheets left these pointing at names
     nothing declares any more, which silently voided the declaration. */
  for (const [from, to] of TOKEN_ALIASES) {
    body = body.replaceAll(new RegExp(`var\\(\\s*${from}(?![\\w-])`, 'g'), `var(${to}`);
  }

  writeFileSync(join(OUT_PAGES, `${id}.ts`),
    `${banner}export const html = ${JSON.stringify(body.trim())};\n`);

  routes.push({
    id, path,
    seo: {
      title, description, keywords, path, ogType, image, robots, author,
      jsonLd: jsonLd.length ? cleanUrls(jsonLd.length === 1 ? jsonLd[0] : jsonLd) : undefined,
    },
  });
}

const entries = routes.map((r) => `  {
    path: ${JSON.stringify(r.path.replace(/^\//, ''))},${r.path === '/' ? "\n    pathMatch: 'full'," : ''}
    component: StaticPage,
    resolve: { html: pageResolver },
    data: {
      seo: ${JSON.stringify(r.seo)},
      pageClass: ${JSON.stringify(`page-${r.id}`)},
      load: () => import('../content/pages/${r.id}'),
    },
  },`);

writeFileSync(join(OUT_DIR, 'page-routes.ts'),
  `${banner}import { Routes } from '@angular/router';\n` +
  `import { StaticPage } from '../pages/static-page';\n` +
  `import { pageResolver } from '../pages/page-resolver';\n\n` +
  `export const pageRoutes: Routes = [\n${entries.join('\n')}\n];\n`);

writeFileSync(join(OUT_CSS, '_index.css'),
  `/* GENERATED by tools/import-pages.mjs */\n` +
  cssFiles.map((f) => `@import './${f}';`).join('\n') + '\n');

console.log(`pages: ${routes.length} imported, ${cssFiles.length} page stylesheets, ` +
  `${droppedRules} duplicated rules dropped, ${missing} missing`);
